### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by BannerBomb** [axetroy/vscode-npm-import-package-version#178]
when I started Visual Studio Code I got this in the output console for npm import version server.
```js
server start
compile: file:///c%3A/Users/Admin/Desktop/Github_Stuff/Discord_Bots/StratoBotElite/branches/master/src/bot/commands/Logging/user-join.js
RangeError: Maximum call stack size exceeded
    at Object.normalize (path.js:265:12)
    at Object.join (path.js:429:18)
    at findPackage (c:\Users\Admin\.vscode\extensions\axetroy.vscode-npm-import-package-version-0.7.5\server\out\utils.js:54:30)
    at findPackage (c:\Users\Admin\.vscode\extensions\axetroy.vscode-npm-import-package-version-0.7.5\server\out\utils.js:60:16)
    at findPackage (c:\Users\Admin\.vscode\extensions\axetroy.vscode-npm-import-package-version-0.7.5\server\out\utils.js:60:16)
    at findPackage (c:\Users\Admin\.vscode\extensions\axetroy.vscode-npm-import-package-version-0.7.5\server\out\utils.js:60:16)
    at findPackage (c:\Users\Admin\.vscode\extensions\axetroy.vscode-npm-import-package-version-0.7.5\server\out\utils.js:60:16)
    at findPackage (c:\Users\Admin\.vscode\extensions\axetroy.vscode-npm-import-package-version-0.7.5\server\out\utils.js:60:16)
    at findPackage (c:\Users\Admin\.vscode\extensions\axetroy.vscode-npm-import-package-version-0.7.5\server\out\utils.js:60:16)
    at findPackage (c:\Users\Admin\.vscode\extensions\axetroy.vscode-npm-import-package-version-0.7.5\server\out\utils.js:60:16)
```

**Comment by cimak** [comment]
Apparently there is some problem with file's URIs on windows:
```js
/**
 * compile the code and return marks
 * @param document
 */
function compile(document) {
    return __awaiter(this, void 0, void 0, function* () {
        const filepath = require("file-uri-to-path")(document.uri);
        
        console.log({
            uri: document.uri,
            filepath,
        });
```
outputs:
```js
{
  uri: 'file:///c%3A/Users/wilk/.vscode/extensions/axetroy.vscode-npm-import-package-version-0.7.5/server/out/parser/index.js',
  filepath: '\\c%3A\\Users\\wilk\\.vscode\\extensions\\axetroy.vscode-npm-import-package-version-0.7.5\\server\\out\\parser\\index.js'
}
```

File name starts with "/c:/Users" instead of "c:/Users".

**Comment by BannerBomb** [comment]
That's a normal file uri though
![image](https://user-images.githubusercontent.com/11788894/100148024-2a898a00-2e6a-11eb-894d-af33ab92eb9a.png)

**Comment by BannerBomb** [comment]
ah, it's the percentage afaik.
![image](https://user-images.githubusercontent.com/11788894/100148367-aa175900-2e6a-11eb-95d0-5633d91afb06.png)

so it's an issue with file-uri-to-path, either the dev of file-uri-to-path or axetroy will need to handle un-escaping the uri.

**Comment by BannerBomb** [comment]
Sorry for adding another comment, But according to [this](https://github.com/TooTallNate/file-uri-to-path/issues/7#issuecomment-540463375) comment on the file-uri-to-path package. Nodejs v10 and up have a File uri to path method already built-in also so axetroy could also just remove the dependency and replace it with the built-in method.
```js
const { fileURLToPath } = require('url');
fileURLToPath("file:///c%3A/Users/Admin/Desktop/Github_Stuff/Discord_Bots/StratoBotElite/branches/master/src/bot/commands/Logging/user-join.js")

/* which returns
 /c:/Users/Admin/Desktop/Github_Stuff/Discord_Bots/StratoBotElite/branches/master/src/bot/commands/Logging/user-join.js*/
```
